name: 'Serverless GitHub Action'
description: 'Wraps the Serverless Framework to enable common Serverless commands'
author: 'Serverless, Inc. <hello@serverless.com> (https://serverless.com)'
branding:
  icon: 'zap'
  color: 'red'
inputs:
  args:
    description: 'Arguments passed to `serverless`'
    required: false
    default: help
  entrypoint:
    description: 'Serverless entrypoint. For example: `/bin/sh`'
    required: false
  serverless-version:
    description: 'Version of the Serverless Framework to use (default: latest)'
    required: false
    default: latest
  working-directory:
    description: 'Folder where your configuration is located'
    required: false
    default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.serverless-version }}
    - ${{ inputs.args }}
  entrypoint: ${{ inputs.entrypoint }}

outputs:
  version:
    description: 'Serverless Framework version'
  result:
    description: 'Serverless Framework result'
